ingress:
  enabled: true
  hosts:
    - ""

zenko-zookeeper:
  servers: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  heap: "256M"

kafka:
  replicas: 1

mongodb-replicaset:
  replicaSet: rs0
  replicas: 3

