apiVersion: v1
kind: Service
metadata:
  name: {{ template "backbeat.fullname" . }}-api
  labels:
    app: {{ template "backbeat.name" . }}
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: 8900
      targetPort: 8900
      protocol: TCP
      name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "backbeat.name" . }}-api
    release: {{ .Release.Name }}
